name: Compile and test

on:
  push

jobs:
  compile_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: snok/install-poetry@v1
      - run: poetry install
      - run: poetry run pytest
